### ISSUE TITLE
JSON request body does not represent an object

### ISSUE THREAD

**Issue by KDederichs** [mollie/mollie-api-php#237]
## Specifications

  - API Version: 2.0.9

## Describe the issue

Hey,

I'm using your API in combination with Symfony 4 and so far it was working fine.
Out of the blue I started to get 
```Error executing API call (400: Bad Request): The JSON request body does not represent an object..```

Errors while trying to create new customers. 

Any idea what could be causing this?

**Comment by Smitsel** [comment]
Can you post a piece of code to give some more context on what you're using?

**Comment by KDederichs** [comment]
Sure, 
the scenario is simple:
I have a doctrine listener that queries the Mollie Api after a new customer is registered to get an ID from you. That is done simply by calling:
```php
    /** @var MollieApiClient */
    private $mollie;

    public function __construct(MollieApiClient $mollie)
    {
        $this->mollie = $mollie;
    }

    public function postPersist(LifecycleEventArgs $args)
    {
        /** @var Customer $customer */
        $customer = $args->getEntity();

        if (!$customer instanceof Customer) {
            return;
        }

        $em = $args->getEntityManager();

       $response = $this->mollie->customers->create();

        if ($response) {
            $customer->setMollieId($response->id);
            $em->persist($customer);
            $em->flush();
        }
    }

 ```

The MollieApiClient is registered as a service and is inject by DI into the listener.
The MollieApiClient is simply registered by setting:

```yaml

    GuzzleHttp\Client:
      alias: eight_points_guzzle.client.defaultClient

    Mollie\Api\MollieApiClient:
        calls:
            - method: setApiKey
              arguments:
                  - '%env(MOLLIE_API_KEY)%'
```
